name: Parallel Workflow

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: run compile
        run: mvn compile

  fast-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: run fast tests
        run: mvn test

  slow-tests:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: run slow tests
        run: mvn integration-test

  verify:
    runs-on: ubuntu-latest
    needs: [fast-tests, slow-tests]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: run verify
        run: mvn verify

      - name: Create success status check
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -d '{"state": "success", "context": "work"}' \
          https://api.github.com/repos/NewEnergyCode/techtask/statuses/$(git rev-parse HEAD)
