name: Workflow

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
    - name: Send status check
      uses: actions/github-script@v6
      with:
        script: |
          const { context, github } = require('@actions/github');
          const status = context.payload.workflow_dispatch ? 'success' : 'failure';
          github.repos.createCommitStatus({
            ...context.repo,
            sha: context.sha,
            state: status,
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: 'The build finished successfully.',
            context: 'work'
          });
