name: Workflow

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
    - name: Create commit status
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const status = {
            state: '${{ job.status }}',
            description: 'The build finished with this status',
            context: 'work'
          };

          const { data: commitStatus } = await github.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            ...status
          });

          console.log(commitStatus);
