name: Workflow

on:
  workflow_dispatch:

jobs:
  work:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
    - name: Create success status check
      run: |
        curl -X POST -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
        -d '{"state": "success", "context": "work"}' \
        https://api.github.com/repos/NewEnergyCode/techtask/statuses/$(git rev-parse HEAD)
